[window]
blur = true
opacity = 0.7
decorations = "Transparent"
dynamic_padding = true

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[window.padding]
y = 30
x = 10

[general]
import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]
